eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8861
spring:
  application:
    name: zuul-server
  security:
    basic:
      enabled: false
    oauth2:
      client:
        access-token-uri: http://localhost:8766/oauth/token #令牌端点
        user-authorization-uri: http://localhost:8766/oauth/authorize #授权端点
        client-id: zuul_server #OAuth2客户端ID
        client-secret: secret #OAuth2客户端密钥
      resource:
        jwt:
          key-value: springcloud123 #使用对称加密方式，默认算法为HS256
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    api-sys:
      path: /api-sys/**
      serviceId: system-web-server